[package]
name = "eepy"
version = "0.1.0"
edition = "2021"
description = "tomorrow... not today... do it tomorrow... todays too hard"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
ratatui = { version = "0.23.0", features = ["all-widgets", "macros"] }
